GET http://localhost:5000/api/comments/
# GET https://rainy-eggnog-production.up.railway.app/api/comments

###
# POST https://rainy-eggnog-production.up.railway.app/api/comments/newReply
POST http://localhost:5000/api/comments/newReply
content-type: application/json

{
  "allComments" : [
  {
    "id": 1,
    "content": "First comment",
    "createdAt": "today",
    "score": 0,
    "user": 4,
    "replyingToComment": null,
    "replyingToUser": null,
    "replies": [
      2
    ]
  },
  {
    "id": 2,
    "content": "another reply!!",
    "createdAt": "today",
    "score": 0,
    "user": 2,
    "replyingToComment": 1,
    "replyingToUser": 4,
    "replies": []
  }
],
  "newComment": {
    "content": "@maxblagun a reply to your reply!!<script>hacked</script>",
    "user": 3,
    "replyingToComment": 2,
    "replyingToUser": 2,
    "replyingToAuthor": "maxblagun<script>hacked</script>"
  }
}

###
# POST https://rainy-eggnog-production.up.railway.app/api/comments/newComment
POST http://localhost:5000/api/comments/newComment
content-type: application/json

{
  "newComment" : {
    "user": 1,
    "content": "content"
  }
}

###
PUT http://localhost:5000/api/comments

###
PUT http://localhost:5000/api/comments
content-type: application/json

{
  "newContent": "content updated with REST Client",
  "commentID": 1
}

###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
content-type: application/json

{
  "username": "adf"
}